
*   **Arewa Data Science Academy**
*   Deep Learning Cohort 2.0
*   Name: Namiru Lawal
*   Email: namirlawal6447@gmail.com
*   Title: Week 1 Solution


In [1]:
# Excercise 1 Solution


In [16]:
#Excercise 2 Solution
# Import torch
import torch

# Create random tensor
A = torch.rand(size=(7, 7))
A, A.shape

(tensor([[0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388],
         [0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665, 0.7399],
         [0.4517, 0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893],
         [0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770],
         [0.4108, 0.0014, 0.5414, 0.6419, 0.2976, 0.7077, 0.4189],
         [0.0655, 0.8839, 0.8083, 0.7528, 0.8988, 0.6839, 0.7658],
         [0.9149, 0.3993, 0.1100, 0.2541, 0.4333, 0.4451, 0.4966]]),
 torch.Size([7, 7]))

In [17]:
#Excercise 3 Solution

# Create another random tensor
B = torch.rand(size=(1, 7))
# C = torch.matmul(A, B) # will error because of shape issues
C = torch.matmul(A, B.T) # no error because of transpose
C, C.shape

(tensor([[2.1391],
         [2.3548],
         [1.6001],
         [1.9384],
         [1.4356],
         [2.1416],
         [1.7684]]),
 torch.Size([7, 1]))

In [18]:
#Excercise 4 Solution

# Set manual seed
torch.manual_seed(0)

# Create two random tensors
A = torch.rand(size=(7, 7))
B = torch.rand(size=(1, 7))

# Matrix multiply tensors
C = torch.matmul(A, B.T)
C, C.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [19]:
# Excercise 5 Solution

# Set random seed on the GPU
torch.cuda.manual_seed(1234)

In [25]:
# Excercise 6 Solution

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B


Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [21]:
# Excercise 7 Solution

# Perform matmul on tensor_A and tensor_B

# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error

tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

In [22]:
# Excercise 8 Solution

# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min

(tensor(0.5617), tensor(0.3647))

In [23]:
# Excercise 9 Solution

# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min


(tensor(3), tensor(0))

In [26]:
# Excercise 10 Solution

# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
